apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: amq-demo
  labels:
    app: activemq
spec:
  replicas:  1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      namespace: amq-demo
      labels:
        app: activemq
        app.kubernetes.io/version: 1.7.3
        app.kubernetes.io/part-of: ActiveMQDemo
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq:5.16.6
          ports:
            - containerPort: 61616
            - containerPort: 8161
          env:
            - name: ACTIVEMQ_ADMIN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: amq-demo-secret
                  key: ACTIVEMQ_USER
            - name: ACTIVEMQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amq-demo-secret
                  key: ACTIVEMQ_PASSWORD
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: amq-demo
spec:
  selector:
    app: activemq
  type: ClusterIP # LoadBalancer
  ports:
    - port: 8161
      protocol: TCP
      targetPort: 8161
    - port: 61616
      protocol: TCP
      targetPort: 61616
