
spring:
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}

app:
  queue-name: ${ACTIVEMQ_QUEUE:demo.queue}

server:
  port: ${SERVER_PORT:8086}
