name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version of the images
        required: true
      publish:
        type: boolean
        description: Publish to the GitHub Registry?
        required: false
        default: false
  push:
    tags:
      - 'v*.*.*'
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set Env Push
      if: ${{ github.event_name == 'push' }}
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set Env Dispatch
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
    - name: Set Env Other
      if: ${{ github.event_name != 'workflow_dispatch' && github.event_name != 'push' }}
      run: echo "RELEASE_VERSION=none" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push producer Ubuntu
      uses: docker/build-push-action@v5
      with:
        context: ./producer-app
        push: ${{ github.event_name == 'push' || inputs.publish }}
        tags: |
          ghcr.io/ihudak/activemq-monitoring-demo-producer:latest
          ghcr.io/ihudak/activemq-monitoring-demo-producer:noble
          ghcr.io/ihudak/activemq-monitoring-demo-producer:${{ env.RELEASE_VERSION }}
          ghcr.io/ihudak/activemq-monitoring-demo-producer:build_${{ github.run_number }}
        platforms: linux/amd64,linux/arm64/v8
        build-args: |
          VER=21
          FLAVOR=noble
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push producer Alpine
      uses: docker/build-push-action@v5
      with:
        context: ./producer-app
        push: ${{ github.event_name == 'push' || inputs.publish }}
        tags: |
          ghcr.io/ihudak/activemq-monitoring-demo-producer:alpine
          ghcr.io/ihudak/activemq-monitoring-demo-producer:${{ env.RELEASE_VERSION }}-alpine
          ghcr.io/ihudak/activemq-monitoring-demo-producer:build_${{ github.run_number }}-alpine
        platforms: linux/amd64,linux/arm64/v8
        build-args: |
          VER=21
          FLAVOR=alpine
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push consumer Ubuntu
      uses: docker/build-push-action@v5
      with:
        context: ./consumer-app
        push: ${{ github.event_name == 'push' || inputs.publish }}
        tags: |
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:latest
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:noble
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:${{ env.RELEASE_VERSION }}
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:build_${{ github.run_number }}
        platforms: linux/amd64,linux/arm64/v8
        build-args: |
          VER=21
          FLAVOR=noble
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push consumer Alpine
      uses: docker/build-push-action@v5
      with:
        context: ./consumer-app
        push: ${{ github.event_name == 'push' || inputs.publish }}
        tags: |
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:alpine
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:${{ env.RELEASE_VERSION }}-alpine
          ghcr.io/ihudak/activemq-monitoring-demo-consumer:build_${{ github.run_number }}-alpine
        platforms: linux/amd64,linux/arm64/v8
        build-args: |
          VER=21
          FLAVOR=alpine
        cache-from: type=gha
        cache-to: type=gha,mode=max
